# Generated by Django 5.1.2 on 2025-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_deleted_at_message_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_for',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
